- hosts: all
  gather_facts: yes

  vars_files:
  - 'vars.yml'

  vars: 
    ansible_become: yes

  tasks:
  - name: set hostname according inventory variable
    shell: "hostnamectl set-hostname {{new_hostname}}"
    when: ( new_hostname is defined ) and ( ansible_facts['nodename'] != new_hostname )
    register: renamed_host

  - name: install epel-release
    yum:
      name: epel-release
      state: latest

  - name: install updates
    yum: 
      name: "*" 
      state: latest
      update_cache: yes

  - name: install net-tools (netstat, ...)
    yum:
      name: net-tools
      state: latest

  - name: disable and stop firewalld
    service:
      name: firewalld
      enabled: no
      state: stopped

  - name: add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_ssh_host }} {{ item }}.{{ subdomain }} {{ item }}"
      state: present
    when: hostvars[item].ansible_ssh_host is defined
    with_items: "{{ groups.all }}"

  - name: restart host if required
    reboot:
    when: renamed_host.changed|bool == True
