---
#file: roles/api/tasks/juice.yml

- name: Pull an juiceshop image
  docker_image:
    name: bkimminich/juice-shop
    source: pull
  become: true

- name: Start a fruitshop container
  docker_container:
    name: juiceshop
    image: bkimminich/juice-shop
    state: started
    ports:
     - "3000:3000"
  become: true


