---
# file: roles/nginx/tasks/nginx.yml

- name: Login to the controller
  uri:
    url: "https://{{ baseurl }}/platform/login"
    method: POST
    body_format: json
    body:
      credentials:
        type: "BASIC"
        username: "{{ email }}"
        password: "{{ password }}"
    status_code: 204
    validate_certs: False
  register: login
  tags: nginx

- name: get the API key from the controller
  uri:
    url: "https://{{ baseurl }}/platform/global"
    headers:
      Cookie: "{{ login.set_cookie }}"
    status_code: 200
    validate_certs: False
  register: globals
  tags: nginx

- name: extract and store the API key
  set_fact: 
    apiKey : "{{ globals.json.currentStatus.agentSettings.apiKey }}"
  tags: nginx

- name: retrieve the controller installer from the NGINX Controller
  get_url:
    dest: /tmp/install.sh
    mode: 0750
    url: https://{{ fqdn }}:8443/1.4/install/controller/
    validate_certs: no
  tags: nginx

- name: Start an nginx container called "cn01"
  docker_container:
    name: cn01
    hostname: cn01
    image: nginx-plus-ctl
    state: started
    recreate: yes
    env:
      CONTROLLER_URL: 'https://{{ fqdn }}/install/controller-agent'
      API_KEY: '{{ apiKey }}'
      LOCATION: 'container'
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
  tags: nginx
  become: true