- hosts: ws
  vars_files:
    - 'vars.yml'
    - '../vars.yml'

  vars: 
    ansible_become: yes

  tasks:
    - include: 'tasks/install_nginxplus.yml'
    - include: 'tasks/copy_configurations.yml'
#    - include: 'tasks/add_upstream_conf.yml'
