- hosts: ctl
  gather_facts: no

  vars_files:
    - 'vars.yml'
    - '../vars.yml'

  tasks:
  - name: Login to the controller
    uri:
      url: "https://{{ baseurl }}/platform/login"
      method: POST
      body_format: json
      body:
        credentials:
          type: "BASIC"
          username: "{{ email }}"
          password: "{{ password }}"
      status_code: 204
      validate_certs: False
    register: login

  - name: create a couple of users    
    uri:
      url: "https://{{ baseurl }}/platform/users"
      method: POST
      headers:
        Cookie: "{{ login.set_cookie }}"
      body_format: json
      body:
        metadata:
          name: "{{ item.firstname | lower }}@{{ subdomain }}"
          tags:
            - "{{ item.title }}"
            - "{{ item.team }}"
        desiredState:
          firstName: "{{ item.firstname }}"
          lastName: "{{ item.lastname }}"
          email: "{{ item.firstname | lower }}@{{ subdomain }}"
          password: "{{ item.password }}"
          roles:
            - links:
                rel: /api/v1/platform/roles/guest
                name: guest
              ref: /platform/roles/guest
      status_code: 200,201
      validate_certs: False
    loop:
      - { firstname: 'Tony', lastname: 'Ashworth', team: 'App Dev', title: 'developer', password: 'Ng1nx123' }
      - { firstname: 'Olivia', lastname: 'Bennett',team: 'Dev Ops', title: 'engineer', password: 'Ng1nx123' }
      - { firstname: 'David', lastname: 'Clay', team: 'Net Ops', title: 'engineer', password: 'Ng1nx123' }
      - { firstname: 'Chris', lastname: 'Davies', team: 'Sec Ops', title: 'engineer', password: 'Ng1nx123' }
      - { firstname: 'Paula', lastname: 'Elliot', team: 'App Owner', title: 'manager', password: 'Ng1nx123' }
      - { firstname: 'April', lastname: 'Flynn', team: 'Support', title: 'engineer',  password: 'Ng1nx123' }
      - { firstname: 'Mike', lastname: 'Gibbons', team: 'Net Ops', title: 'manager', password: 'Ng1nx123' }

