---
# file: roles/ctl-setup/tasks/demo_api.yml

- name: Login to the controller
  uri:
    url: "https://{{ baseurl }}/platform/login"
    method: POST
    body_format: json
    body:
      credentials:
        type: "BASIC"
        username: "{{ email }}"
        password: "{{ password }}"
    status_code: 204
    validate_certs: False
  register: login
  tags: demo

# Demo-API web app
- name: Create/configure demo-api web app
  uri:
    url: "https://{{ baseurl }}/services/environments/lab/apps/www_web"
    method: PUT
    headers:
      Cookie: "{{ login.set_cookie }}"
    body_format: json
    body: >
      {
        "metadata": {
          "name": "www_web",
          "displayName": "",
          "description": "",
          "tags": []
        },
        "desiredState": {}
      }
    status_code: 200, 201, 202
    validate_certs: False
  tags: demo

# Demo-API web app component
- name: Create/configure demo-api web component
  uri:
    url: "https://{{ baseurl }}/services/environments/lab/apps/www_web/components/www_web_comp"
    method: PUT
    headers:
      Cookie: "{{ login.set_cookie }}"
    body_format: json
    body: >
      {
        "metadata": {
          "name": "www_web_comp",
          "tags": []
        },
        "desiredState": {
          "ingress": {
            "gatewayRefs": [
              {
                "ref": "/services/environments/lab/gateways/www.{{ subdomain }}-gw"
              }
            ],
            "uris": {
              "/": {
                "matchMethod": "EXACT"
              },
              "/dashboard": {
                "matchMethod": "EXACT"
              },
              "/login": {
                "matchMethod": "EXACT"
              },
              "/oidc/callback": {
                "matchMethod": "EXACT"
              }
            }
          },
          "backend": {
            "ntlmAuthentication": "DISABLED",
            "preserveHostHeader": "DISABLED",
            "workloadGroups": {
              "flaskapp_wlg": {
                "locationRefs": [
                  {
                    "ref": "/infrastructure/locations/unspecified"
                  }
                ],
                "loadBalancingMethod": {
                  "type": "ROUND_ROBIN"
                },
                "uris": {
                  "http://sigw.lab.leyux.org:5000": {
                    "isBackup": false,
                    "isDown": false,
                    "isDrain": false
                  }
                }
              }
            }
          },
          "logging": {
            "errorLog": "DISABLED",
            "accessLog": {
              "state": "DISABLED"
            }
          },
          "security": {}
        }
      }
    status_code: 200, 201, 202
    validate_certs: False
  tags: demo

# Demo-API demo-api
- name: Create/configure demo-api
  uri:
    url: "https://{{ baseurl }}/services/api-definitions/demo-api/versions/1.0.0"
    method: PUT
    headers:
      Cookie: "{{ login.set_cookie }}"
    body_format: json
    body: >
      {
        "metadata": {
          "name": "1.0.0",
          "displayName": "DEMO-API",
          "description": "",
          "tags": []
        },
        "desiredState": {
          "specs": {
            "REST": {
              "openapi": "3.0.0",
              "info": {
                "license": {
                  "name": "MIT"
                },
                "title": "DEMO-API",
                "version": "1.0.0"
              },
              "paths": {
                "/greet": {
                  "x-controller-match-method": "EXACT",
                  "get": {
                    "summary": "Greeting",
                    "responses": {
                      "200": {
                        "description": "Greeting",
                        "content": {
                          "application/json": {
                            "schema": {
                              "type": "string"
                            }
                          }
                        }
                      },
                      "default": {
                        "description": "unexpected error",
                        "content": {
                          "application/json": {
                            "schema": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    status_code: 200, 201, 202
    validate_certs: False
  tags: demo

# Demo-API demo-api publish
- name: Publish demo-api
  uri:
    url: "https://{{ baseurl }}/services/environments/lab/apps/www_web/published-apis/demo-api"
    method: PUT
    headers:
      Cookie: "{{ login.set_cookie }}"
    body_format: json
    body: >
      {
        "metadata": {
          "name": "demo-api",
          "tags": []
        },
        "desiredState": {
          "apiDefinitionVersionRef": {
            "ref": "/services/api-definitions/demo-api/versions/1.0.0"
          },
          "gatewayRefs": [
            {
              "ref": "/services/environments/lab/gateways/www.{{ subdomain }}-gw"
            }
          ],
          "devportalRefs": [
            {
              "ref": "/services/environments/lab/devportals/devportal"
            }
          ],
          "basePath": "/v1",
          "stripWorkloadBasePath": true
        }
      }
    status_code: 200, 201, 202
    validate_certs: False
  tags: demo

# Demo-API demo-api component
- name: Create/config demo-api component
  uri:
    url: "https://{{ baseurl }}/services/environments/lab/apps/www_web/components/demo-api_comp"
    method: PUT
    headers:
      Cookie: "{{ login.set_cookie }}"
    body_format: json
    body: >
      {
        "metadata": {
          "createTime": "2020-10-13T14:43:00Z",
          "kind": "components",
          "links": {
            "rel": "/api/v1/services/environments/lab/apps/www_web/components/demo-api_comp"
          },
          "name": "demo-api_comp",
          "uid": "99eb1417-1e18-4436-b24c-edc7dddce3ef",
          "updateTime": "2020-10-13T14:43:00Z"
        },
        "desiredState": {
          "backend": {
            "ntlmAuthentication": "DISABLED",
            "preserveHostHeader": "DISABLED",
            "workloadGroups": {
              "demo_api_wlg": {
                "loadBalancingMethod": {
                  "type": "ROUND_ROBIN"
                },
                "locationRefs": [
                  {
                    "links": {
                      "rel": "/api/v1/infrastructure/locations/unspecified",
                      "displayName": "Unspecified (default)",
                      "name": "unspecified"
                    },
                    "ref": "/infrastructure/locations/unspecified"
                  }
                ],
                "uris": {
                  "http://sigw.lab.leyux.org:5000": {
                    "isBackup": false,
                    "isDown": false,
                    "isDrain": false
                  }
                }
              }
            }
          },
          "ingress": {
            "uris": {
              "/greet": {
                "matchMethod": "EXACT"
              }
            },
            "gatewayRefs": [
              {
                "ref": "/services/environments/lab/gateways/www.{{ subdomain }}-gw"
              }
            ]
          },
          "logging": {
            "accessLog": {
              "state": "DISABLED"
            },
            "errorLog": "DISABLED"
          },
          "publishedApiRefs": [
            {
              "ref": "/services/environments/lab/apps/www_web/published-apis/demo-api"
            }
          ],
          "security": {}
        }
      }
    status_code: 200, 201, 202
    validate_certs: False
  tags: demo

