- uri:
    url: http://{{ nginxplus_api_server }}/api/3/http/upstreams/backend/servers/
    method: POST
    body_format: json
    body:
      server: "{{ ansible_default_ipv4.address }}:{{ nginx_ws_port }}"
    status_code: 201