- name: copy nginx-plus configuration file default.conf
  template: src=etc/nginx/conf.d/default.conf dest=/etc/nginx/conf.d/default.conf owner=root mode=0644

- name: copy nginx-plus configuration file hello.conf
  template: src=etc/nginx/conf.d/hello.conf dest=/etc/nginx/conf.d/hello.conf owner=root mode=0644

- name: copy nginx-plus configuration file nginx.conf	
  template: src=etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=0644

- name: copy nginx-plus configuration file nginx-plus-api.conf
  template: src=etc/nginx/conf.d/nginx-plus-api.conf dest=/etc/nginx/conf.d/nginx-plus-api.conf owner=root mode=0644

- name: copy custom index.html
  template: src=usr/share/nginx/html/index.html dest=/usr/share/nginx/html/index.html owner=root mode=0644


- name: reload nginx
  service:
    name: nginx
    state: restarted
